# Generated by Django 3.1.4 on 2020-12-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='item',
        ),
        migrations.RemoveField(
            model_name='client',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.client')),
            ],
        ),
    ]
